### ISSUE TITLE
Incorrect height setting of window

### ISSUE THREAD

**Issue by konsvasi** [itaditya/trick-or-treat-game#43]
At the moment the width and height calculations doesn't take into consideration the padding that has been set in the game class. This lead to scrollbars appearing in the mobile version even though there is no more content when scrolling. In the desktop version the whole window will move up/down and left/right when the user moves the player.

As a solution I would calculate the height by removing the padding that has been set so there is no more scrollable space on the screen. 

I'll work on it, if you have any suggestions feel free to comment

**Comment by itaditya** [comment]
just adding `box-sizing: border-box` fixed it in this commit https://github.com/itaditya/trick-or-treat-game/commit/9da27db7cde771842f71eb4ba8411ed28751bcfc

Closing the issue. Also doing a calc with subtracting padding would not be very maintanable because if somebody changes the padding, somebody has to remember to also update the calc in height. Though in this case, CSS custom properties can help.
