### ISSUE TITLE
Add a restart button or shortcut for the same

### ISSUE THREAD

**Issue by ashokdey** [itaditya/trick-or-treat-game#50]
- While playing the game I should be able to restart it midway. 
- This same restart button will solve the bad UX of refreshing the page. 
- Even if refreshing is the option to restart, **don't let the user know** that you are actually refreshing

**Comment by itaditya** [comment]
There's an issue already open for that https://github.com/itaditya/trick-or-treat-game/issues/26.

Regarding that, I opened a PR https://github.com/itaditya/trick-or-treat-game/pull/34

But I recently got a PR to add service worker to the game. With service workers, all game assets will be cached, and so even if we do `window.reload()` from a button, it will be very quick. So I'm waiting for the service worker PR to get merged.

Closing this because this one is duplicate.
